version: "3.7"

services:
  prometheus:
    image: "prom/prometheus"
    container_name: grumplyclient-prometheus
    ports:
      - "9090:9090"
    expose:
      - 9090
    volumes:
      - ./prometheus_cfg.yaml:/etc/prometheus/cfg.yaml
    command:
      - "--storage.tsdb.retention.time=30d"
      - "--config.file=/etc/prometheus/cfg.yaml"
    networks:
      - grumpy-network

  mongodb:
    container_name: grumplyclient-mongodb
    image: mongo
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    environment:
      MONGO_INITDB_ROOT_USERNAME: $MONGO_USERNAME
      MONGO_INITDB_ROOT_PASSWORD: $MONGO_PASS
    ports:
      - "27017:27017"
    expose:
      - 27017
    volumes:
      - mongodb-volume:/data/db
    networks:
      - grumpy-network

volumes:
  mongodb-volume:
    driver: local

networks:
  grumpy-network:
    driver: bridge
